'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3603
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class UserControls_wuc_NuevoIngreso

    '''<summary>
    '''Control dgv_Empleados.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents dgv_Empleados As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Control tbc_Datos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbc_Datos As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''Control tab_Generales.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tab_Generales As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Control pnl_DatosG.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents pnl_DatosG As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Control tbx_Clave.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Clave As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NombreCompleto.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NombreCompleto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Mail.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Mail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Nombres.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Nombres As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Telefono.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Telefono As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_ApellidoPaterno.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_ApellidoPaterno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_TelefonoMovil.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_TelefonoMovil As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_ApellidoMaterno.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_ApellidoMaterno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Elector.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Elector As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Departamento.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Departamento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_RFC.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_RFC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Puesto.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Puesto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CURP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CURP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Calle.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Calle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_IMSS.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_IMSS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_EntreCalle1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_EntreCalle1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_UMF.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_UMF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_EntreCalle2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_EntreCalle2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NumCartilla.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NumCartilla As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NumExterior.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NumExterior As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NumInterior.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NumInterior As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NumPasaporte.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NumPasaporte As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Colonia.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Colonia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_TipoLicencia.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_TipoLicencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Ciudad.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Ciudad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_FechaExpira.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_FechaExpira As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Zona.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Zona As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rdb_SiINFONAVIT.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_SiINFONAVIT As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_NoINFONAVIT.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_NoINFONAVIT As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_Masculino.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_Masculino As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_Femenino.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_Femenino As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_SiCatFirmas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_SiCatFirmas As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_NoCatFirmas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_NoCatFirmas As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_SiConFam.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_SiConFam As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_NoConFam.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_NoConFam As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_SiCertif.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_SiCertif As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_NoCertif.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_NoCertif As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control tbx_EstadoCivil.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_EstadoCivil As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CantidadHijos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CantidadHijos As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_FechaVenceCred.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_FechaVenceCred As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_ModoNac.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_ModoNac As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Edad.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Edad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_EmpleadoRef.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_EmpleadoRef As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_LugarNac.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_LugarNac As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_FechaIngreso.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_FechaIngreso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_PaisNac.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_PaisNac As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rdb_SiJefe.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_SiJefe As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_NoJefe.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_NoJefe As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control tbx_FechaNac.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_FechaNac As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rdb_SiSaleRuta.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_SiSaleRuta As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_NoSaleRuta.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_NoSaleRuta As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control tbx_FechaNaturalizacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_FechaNaturalizacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rdb_SiVerificaDepositos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_SiVerificaDepositos As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_NoVerificaDepositos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_NoVerificaDepositos As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control tab_Rasgos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tab_Rasgos As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Control tbx_Complexion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Complexion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_TipoSangre.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_TipoSangre As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_UsaAnteojos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_UsaAnteojos As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_PielColor.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_PielColor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_FactorRH.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_FactorRH As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Peso.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Peso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Cara.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Cara As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Estatura.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Estatura As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CabelloCantidad.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CabelloCantidad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_FrenteAltura.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_FrenteAltura As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CejasDireccion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CejasDireccion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CabelloColor.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CabelloColor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_FrenteInclinacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_FrenteInclinacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CejasImplantacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CejasImplantacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CabelloForma.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CabelloForma As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_FrenteAncho.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_FrenteAncho As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CejasForma.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CejasForma As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CabelloCalvicie.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CabelloCalvicie As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CejasTamaño.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CejasTamaño As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CabelloImplantacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CabelloImplantacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_OjosColor.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_OjosColor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NarizRaiz.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NarizRaiz As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_BocaTamaño.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_BocaTamaño As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_OjosForma.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_OjosForma As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NarizDorso.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NarizDorso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_BocaComisuras.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_BocaComisuras As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_OjosTamaño.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_OjosTamaño As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NarizAncho.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NarizAncho As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NarizBase.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NarizBase As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_LabiosEspesor.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_LabiosEspesor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NarizAltura.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NarizAltura As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_LabiosAltura.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_LabiosAltura As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_LabiosProminencia.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_LabiosProminencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_MentonTipo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_MentonTipo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_OrejaForma.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_OrejaForma As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_HelixSuperior.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_HelixSuperior As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_MentonForma.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_MentonForma As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_OrejaOriginal.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_OrejaOriginal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_HelixPosterior.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_HelixPosterior As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_MentonInclinacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_MentonInclinacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_HelixAdherencia.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_HelixAdherencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_LobuloAdherencia.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_LobuloAdherencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_HelixContorno.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_HelixContorno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_LobuloParticularidad.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_LobuloParticularidad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_LobuloDimension.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_LobuloDimension As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tab_Escolares.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tab_Escolares As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Control tbx_UltimosEstudios.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_UltimosEstudios As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Documentacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Documentacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NombreEscuela.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NombreEscuela As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Carrera.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Carrera As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CedulaProfesional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CedulaProfesional As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Especialidad.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Especialidad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_AInicio.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_AInicio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_ATermino.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_ATermino As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Folio.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Folio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Promedio.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Promedio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control dgv_Cursos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents dgv_Cursos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Control tab_Familiares.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tab_Familiares As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Control dgv_Familiares.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents dgv_Familiares As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Control tab_Empleos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tab_Empleos As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Control dgv_Empleos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents dgv_Empleos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Control pnl_EmpleosDetalle.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents pnl_EmpleosDetalle As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Control tbx_NombreEmpresaE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NombreEmpresaE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CalleE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CalleE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_EntreCalle1E.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_EntreCalle1E As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_EntreCalle2E.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_EntreCalle2E As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NumeroExteriorE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NumeroExteriorE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NumeroInteriorE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NumeroInteriorE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_ColoniaE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_ColoniaE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CiudadE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CiudadE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CPE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CPE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_TelefonoE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_TelefonoE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_FechaIngresoE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_FechaIngresoE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_FechaBajaE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_FechaBajaE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rdb_SiSeguridadE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_SiSeguridadE As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_NoSeguridadE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_NoSeguridadE As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_SiPorteArmas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_SiPorteArmas As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_NoPorteArmas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_NoPorteArmas As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control tbx_PuestoE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_PuestoE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NombreJefeE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NombreJefeE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_PuestoJefeE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_PuestoJefeE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_SueldoIE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_SueldoIE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_SueldoFE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_SueldoFE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_MotivoSeparacionE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_MotivoSeparacionE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_OtroMotivoE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_OtroMotivoE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tab_Referencias.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tab_Referencias As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Control dgv_Referencias.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents dgv_Referencias As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Control tab_Varios.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tab_Varios As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Control tbx_IngresoFamiliar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_IngresoFamiliar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_GastoFamiliar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_GastoFamiliar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_IngresoAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_IngresoAdicional As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_DescripcionAdicional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_DescripcionAdicional As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_TipoVivienda.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_TipoVivienda As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_PagoMensual.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_PagoMensual As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_ValorVivienda.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_ValorVivienda As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rdb_SiVehiculo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_SiVehiculo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_NoVehiculo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_NoVehiculo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control tbx_Modelo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Modelo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_ValorVehiculo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_ValorVehiculo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Vicios.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Vicios As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Idiomas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Idiomas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_ActividadesCulturales.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_ActividadesCulturales As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Habilidades.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Habilidades As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control dgv_Señas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents dgv_Señas As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Control tab_Papeleria.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tab_Papeleria As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Control chb_ActaNac.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chb_ActaNac As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chb_ActaMatrimonio.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chb_ActaMatrimonio As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chb_IMSS.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chb_IMSS As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chb_CompDom.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chb_CompDom As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chb_IFE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chb_IFE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chb_CompEstudios.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chb_CompEstudios As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chb_Cartilla.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chb_Cartilla As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chb_Recomendacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chb_Recomendacion As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chb_NoAntecedentes.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chb_NoAntecedentes As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chb_Fotografias.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chb_Fotografias As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chb_CURP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chb_CURP As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chb_Huellas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chb_Huellas As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control tab_Fotos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tab_Fotos As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Control ICompleto.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ICompleto As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Control IFrente.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents IFrente As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Control IDerecho.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents IDerecho As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Control IIzquierdo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents IIzquierdo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Control IFirma.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents IFirma As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Control pnl_Firma.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents pnl_Firma As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Control tbx_Comentarios.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Comentarios As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfv_Comentarios.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfv_Comentarios As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control tbx_Contrasena.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Contrasena As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfv_Contrasena.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfv_Contrasena As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control btn_Aceptar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btn_Aceptar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Control VAL1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents VAL1 As Global.System.Web.UI.WebControls.ValidationSummary
End Class
