'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3603
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class UserControls_wuc_Prospectos

    '''<summary>
    '''Control dgv_Prospectos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents dgv_Prospectos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Control pnl_DatosTodosP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents pnl_DatosTodosP As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Control tbc_DatosProspecto.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbc_DatosProspecto As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''Control tab_GeneralesP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tab_GeneralesP As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Control pnl_DatosG.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents pnl_DatosG As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Control tbx_NombreCompletoP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NombreCompletoP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_MailP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_MailP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NombresP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NombresP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_TelefonoP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_TelefonoP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_ApellidoPaternoP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_ApellidoPaternoP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_TelefonoMovilP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_TelefonoMovilP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_ApellidoMaternoP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_ApellidoMaternoP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_ElectorP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_ElectorP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_DepartamentoP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_DepartamentoP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_RFCP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_RFCP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_PuestoP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_PuestoP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CURPP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CURPP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CalleP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CalleP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_IMSSP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_IMSSP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_EntreCalle1P.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_EntreCalle1P As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_UMFP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_UMFP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_EntreCalle2P.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_EntreCalle2P As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NumCartillaP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NumCartillaP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NumExteriorP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NumExteriorP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NumInteriorP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NumInteriorP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_NumPasaporteP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_NumPasaporteP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_ColoniaP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_ColoniaP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_TipoLicenciaP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_TipoLicenciaP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CiudadP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CiudadP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_FechaExpiraP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_FechaExpiraP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_ZonaP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_ZonaP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CPP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CPP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rdb_SiCatFirmasP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_SiCatFirmasP As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_NoCatFirmasP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_NoCatFirmasP As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_MasculinoP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_MasculinoP As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_FemeninoP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_FemeninoP As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_SiCertifP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_SiCertifP As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_NoCertifP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_NoCertifP As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_SiConFamP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_SiConFamP As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_NoConFamP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_NoConFamP As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control tbx_EmpleadoRefP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_EmpleadoRefP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_EstadoCivilP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_EstadoCivilP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_CantidadHijosP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_CantidadHijosP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rdb_SiJefeP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_SiJefeP As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_NoJefeP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_NoJefeP As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control tbx_ModoNacP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_ModoNacP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_EdadP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_EdadP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_LugarNacP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_LugarNacP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_PaisNacP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_PaisNacP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_FechaNacP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_FechaNacP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_FechaNaturalizacionP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_FechaNaturalizacionP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tab_Entrevistas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tab_Entrevistas As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Control dgv_Entrevistas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents dgv_Entrevistas As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Control pnl_Firma.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents pnl_Firma As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Control tbx_FechaEntrevista.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_FechaEntrevista As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control FilteredTextBoxExtender3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents FilteredTextBoxExtender3 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''Control CalendarExtender3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents CalendarExtender3 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''Control rdb_AptoP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_AptoP As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control rdb_NoAptoP.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rdb_NoAptoP As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control tbx_Comentarios.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Comentarios As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control tbx_Contrasena.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tbx_Contrasena As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control btn_Aceptar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btn_Aceptar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Control ValidationSummary1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary
End Class
